**HERNANDEZ RUBIO DAIRA SAYURI**

**PROYECTO 2**

**CALCULO DE LA INVERSA DE UNA MATRIZ Y SU DETERMINANTE** 

CALCULA LA INEVERSA DE UNA MATRIZ 

In [36]:
import numpy as np
a= int(input('Numero de renglones: '))  #Aqui pedimos al usario el numero de renglones y columnas  
b= int(input('Numero de columnas: '))
matriz = numpy.zeros((a,b))     #es para llenar la matriz con ceros 
vector= numpy.zeros((b))        #alamcenar los valores del vector 
x=numpy.zeros((a))              #alamcenar los resultados despues del proceso de operacion 
print('Introduce la matriz de coeficientes')

for r in range(0,a):        #r= son los renglones
    for c in range(0,b):    #c = son las columnas 
        matriz[(r),(c)]=(input("Elemento a["+str(r+1)+","+str(c+1)+"] "))   #escribir los numeros dentro de la matriz   
print(matriz)       #Imprimir la matriz que tenemos 

print("LA INVERSA DE LA MATRIZ ES: ")
np.linalg.inv(matriz)



Numero de renglones: 2
Numero de columnas: 2
Introduce la matriz de coeficientes
Elemento a[1,1] -7
Elemento a[1,2] 33
Elemento a[2,1] 4
Elemento a[2,2] -19
[[ -7.  33.]
 [  4. -19.]]
LA INVERSA DE LA MATRIZ ES: 


array([[-19., -33.],
       [ -4.,  -7.]])

CALCULA LA DETERMINANTE DE UNA MATRIZ 

In [37]:
import numpy as np
a= int(input('Numero de renglones: '))  #Aqui pedimos al usario el numero de renglones y columnas  
b= int(input('Numero de columnas: '))
matriz = numpy.zeros((a,b))     #es para llenar la matriz con ceros 
vector= numpy.zeros((b))        #alamcenar los valores del vector 
x=numpy.zeros((a))              #alamcenar los resultados despues del proceso de operacion 
print('Introduce la matriz de coeficientes')

for r in range(0,a):        #r= son los renglones
    for c in range(0,b):    #c = son las columnas 
        matriz[(r),(c)]=(input("Elemento a["+str(r+1)+","+str(c+1)+"] "))   #escribir los numeros dentro de la matriz   
print(matriz)       #Imprimir la matriz que tenemos 

print("LA DETERMINANTE DE LA MATRIZ ES:")
np.linalg.det(matriz)

Numero de renglones: 2
Numero de columnas: 2
Introduce la matriz de coeficientes
Elemento a[1,1] 3
Elemento a[1,2] -1
Elemento a[2,1] -2
Elemento a[2,2] 2
[[ 3. -1.]
 [-2.  2.]]
LA DETERMINANTE DE LA MATRIZ ES:


4.000000000000001